"""initial schema

Revision ID: a0043f410bda
Revises: 
Create Date: 2026-06-08 09:54:25.637609
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a0043f410bda'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('site', sa.String(length=32), nullable=True),
    sa.Column('asn', sa.BigInteger(), nullable=False),  # DN42 ASN 超 int32 → BigInteger
    sa.Column('router_id', sa.String(length=64), nullable=False),
    sa.Column('loopback_ipv4', sa.String(length=64), nullable=True),
    sa.Column('loopback_ipv6', sa.String(length=64), nullable=True),
    sa.Column('ipv4_prefixes', sa.JSON(), nullable=False),
    sa.Column('ipv6_prefixes', sa.JSON(), nullable=False),
    sa.Column('inventory', sa.JSON(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('base_template', sa.JSON(), nullable=False),
    sa.Column('current_generation', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('node_id', name=op.f('pk_nodes'))
    )
    op.create_table('agent_tokens',
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], name=op.f('fk_agent_tokens_node_id_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_agent_tokens'))
    )
    op.create_index(op.f('ix_agent_tokens_node_id'), 'agent_tokens', ['node_id'], unique=False)
    op.create_table('dns_zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], name=op.f('fk_dns_zones_node_id_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dns_zones')),
    sa.UniqueConstraint('node_id', 'name', name='uq_dns_zones_node_id_name')
    )
    op.create_index(op.f('ix_dns_zones_node_id'), 'dns_zones', ['node_id'], unique=False)
    op.create_table('enrollment_tokens',
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], name=op.f('fk_enrollment_tokens_node_id_nodes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_enrollment_tokens'))
    )
    op.create_table('generations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], name=op.f('fk_generations_node_id_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generations')),
    sa.UniqueConstraint('node_id', 'generation', name='uq_generations_node_id_generation')
    )
    op.create_index(op.f('ix_generations_node_id'), 'generations', ['node_id'], unique=False)
    op.create_table('peerings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('local_node_id', sa.String(length=64), nullable=False),
    sa.Column('remote_node_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('remote_asn', sa.BigInteger(), nullable=False),  # DN42 ASN 超 int32
    sa.Column('remote_label', sa.String(length=128), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['local_node_id'], ['nodes.node_id'], name=op.f('fk_peerings_local_node_id_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['remote_node_id'], ['nodes.node_id'], name=op.f('fk_peerings_remote_node_id_nodes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_peerings')),
    sa.UniqueConstraint('local_node_id', 'name', name='uq_peerings_local_node_id_name')
    )
    op.create_index(op.f('ix_peerings_local_node_id'), 'peerings', ['local_node_id'], unique=False)
    op.create_index(op.f('ix_peerings_remote_node_id'), 'peerings', ['remote_node_id'], unique=False)
    op.create_table('bgp_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('peering_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('remote_asn', sa.BigInteger(), nullable=False),  # DN42 ASN 超 int32
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], name=op.f('fk_bgp_sessions_node_id_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['peering_id'], ['peerings.id'], name=op.f('fk_bgp_sessions_peering_id_peerings'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bgp_sessions')),
    sa.UniqueConstraint('node_id', 'name', name='uq_bgp_sessions_node_id_name')
    )
    op.create_index(op.f('ix_bgp_sessions_node_id'), 'bgp_sessions', ['node_id'], unique=False)
    op.create_index(op.f('ix_bgp_sessions_peering_id'), 'bgp_sessions', ['peering_id'], unique=False)
    op.create_table('wg_interfaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('peering_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], name=op.f('fk_wg_interfaces_node_id_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['peering_id'], ['peerings.id'], name=op.f('fk_wg_interfaces_peering_id_peerings'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wg_interfaces')),
    sa.UniqueConstraint('node_id', 'name', name='uq_wg_interfaces_node_id_name')
    )
    op.create_index(op.f('ix_wg_interfaces_node_id'), 'wg_interfaces', ['node_id'], unique=False)
    op.create_index(op.f('ix_wg_interfaces_peering_id'), 'wg_interfaces', ['peering_id'], unique=False)
    # ### end Alembic commands ###

    # node_routing / node_routing_events 是早期经 create_all 建立、从未有建表迁移的两张
    # 路由表（后续迁移 e1f2a3b4c5d6 / f2a3b4c5d6e7 / a3b4c5d6e7f8 却引用/删列它们，导致
    # alembic 从空库跑会因表不存在而崩）。这里在初始迁移补建它们的**历史 schema**——含
    # 后被 f2a3b4c5d6e7 删的 `routes`、被 a3b4c5d6e7f8 删的 `rpki_unknown`——使那些删列迁移
    # 自然生效、链可从零跑通。生产用 create_all（不跑 alembic）不受影响。
    op.create_table(
        'node_routing',
        sa.Column('node_id', sa.String(length=64), nullable=False),
        sa.Column('observation', sa.String(length=16), nullable=False),
        sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('route_count', sa.Integer(), nullable=False),
        sa.Column('route_count_v4', sa.Integer(), nullable=False),
        sa.Column('route_count_v6', sa.Integer(), nullable=False),
        sa.Column('rpki_valid', sa.Integer(), nullable=False),
        sa.Column('rpki_invalid', sa.Integer(), nullable=False),
        sa.Column('rpki_not_found', sa.Integer(), nullable=False),
        sa.Column('rpki_unknown', sa.Integer(), nullable=True),  # 历史列，由 a3b4c5d6e7f8 删除
        sa.Column('routes', sa.JSON(), nullable=True),  # 历史列，由 f2a3b4c5d6e7 删除
        sa.Column('aggregates', sa.JSON(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], name=op.f('fk_node_routing_node_id_nodes'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('node_id', name=op.f('pk_node_routing')),
    )
    op.create_table(
        'node_routing_events',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('node_id', sa.String(length=64), nullable=False),
        sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('route_count', sa.Integer(), nullable=False),
        sa.Column('route_count_v4', sa.Integer(), nullable=False),
        sa.Column('route_count_v6', sa.Integer(), nullable=False),
        sa.Column('rpki_valid', sa.Integer(), nullable=False),
        sa.Column('rpki_invalid', sa.Integer(), nullable=False),
        sa.Column('rpki_not_found', sa.Integer(), nullable=False),
        sa.Column('rpki_unknown', sa.Integer(), nullable=True),  # 历史列，由 a3b4c5d6e7f8 删除
        sa.Column('announced', sa.Integer(), nullable=False),
        sa.Column('withdrawn', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], name=op.f('fk_node_routing_events_node_id_nodes'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_node_routing_events')),
    )
    op.create_index(op.f('ix_node_routing_events_node_id'), 'node_routing_events', ['node_id'], unique=False)
    op.create_index(op.f('ix_node_routing_events_created_at'), 'node_routing_events', ['created_at'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_routing_events_created_at'), table_name='node_routing_events')
    op.drop_index(op.f('ix_node_routing_events_node_id'), table_name='node_routing_events')
    op.drop_table('node_routing_events')
    op.drop_table('node_routing')
    op.drop_index(op.f('ix_wg_interfaces_peering_id'), table_name='wg_interfaces')
    op.drop_index(op.f('ix_wg_interfaces_node_id'), table_name='wg_interfaces')
    op.drop_table('wg_interfaces')
    op.drop_index(op.f('ix_bgp_sessions_peering_id'), table_name='bgp_sessions')
    op.drop_index(op.f('ix_bgp_sessions_node_id'), table_name='bgp_sessions')
    op.drop_table('bgp_sessions')
    op.drop_index(op.f('ix_peerings_remote_node_id'), table_name='peerings')
    op.drop_index(op.f('ix_peerings_local_node_id'), table_name='peerings')
    op.drop_table('peerings')
    op.drop_index(op.f('ix_generations_node_id'), table_name='generations')
    op.drop_table('generations')
    op.drop_table('enrollment_tokens')
    op.drop_index(op.f('ix_dns_zones_node_id'), table_name='dns_zones')
    op.drop_table('dns_zones')
    op.drop_index(op.f('ix_agent_tokens_node_id'), table_name='agent_tokens')
    op.drop_table('agent_tokens')
    op.drop_table('nodes')
    # ### end Alembic commands ###
