from __future__ import annotations

"""`dn42_common` —— 跨包共享的纯工具层。

平展导出全部子模块的公开 API（校验器 / 常量 / Jinja 环境 / 标签 /
命名规则），使下游包可以开箱即用：

    from dn42_common import validate_asn, validate_dn42_ipv4_network

详见 packages/docs/dn42_common.md。
不得 import 任何业务包。
"""

from .crypto import (
    derive_wireguard_public_key,
    generate_recovery_keypair,
    generate_wireguard_keypair,
    recovery_key_fingerprint,
    seal_to_recovery_key,
    unseal_with_recovery_key,
)
from .communities import (
    DN42_COUNTRY_ORIGIN_COMMUNITY_MAX,
    DN42_COUNTRY_ORIGIN_COMMUNITY_MIN,
    DN42_COUNTRY_ORIGIN_OFFSET,
    DN42_STANDARD_ORIGIN_REGION_COMMUNITIES,
    Dn42OriginRegionCommunity,
    dn42_country_origin_community,
    is_valid_dn42_country_origin_community,
)
from .io import atomic_write_json, atomic_write_text
from .jinja import create_environment, shell_quote, yaml_quote
from .serialization import canonical_json_dumps, canonical_sha256_hex
from .labels import (
    LABEL_COMPONENT,
    LABEL_CONFIG_HASH,
    LABEL_MANAGED,
    LABEL_MANAGED_VALUE,
    LABEL_NODE_ID,
    container_labels,
    network_labels,
    node_id_filter,
)
from .naming import (
    agent_id_for,
    node_project_name,
    normalize_identifier,
    service_container_name,
)
from .validators import (
    DN42_ANYCAST_IPV4_PREFIXES,
    DN42_ANYCAST_IPV6_SPACE,
    DN42_CLOSED_IPV4_PREFIXES,
    DN42_IPV4_SPACE,
    DN42_IPV6_SPACE,
    DN42_RESERVED_IPV4_PREFIXES,
    DN42_TRANSFER_IPV4_PREFIXES,
    PRIVATE_ASN_16BIT_RANGE,
    PRIVATE_ASN_32BIT_RANGE,
    is_address_in_prefix,
    is_agent_token,
    is_dn42_address,
    is_dn42_anycast_address,
    is_dn42_anycast_network,
    is_dn42_closed_network,
    is_dn42_ipv4_address,
    is_dn42_ipv4_network,
    is_dn42_ipv6_address,
    is_dn42_ipv6_network,
    is_dn42_network,
    is_dn42_reserved_network,
    is_dn42_transfer_network,
    is_dn42_zone,
    is_domain_name,
    is_ipv6_link_local,
    is_private_asn,
    is_wireguard_key,
    split_ipv6_zone,
    validate_agent_token,
    validate_asn,
    validate_dn42_ipv4_network,
    validate_dn42_ipv6_network,
    validate_domain_name,
    validate_hostname,
    validate_ip_address,
    validate_ip_address_with_optional_zone,
    validate_ip_interface,
    validate_ip_network,
    validate_ipv6_link_local_address,
    validate_iso8601_timestamp,
    validate_wireguard_endpoint,
    validate_wireguard_key,
)


__all__ = [
    "DN42_ANYCAST_IPV4_PREFIXES",
    "DN42_ANYCAST_IPV6_SPACE",
    "DN42_CLOSED_IPV4_PREFIXES",
    "DN42_COUNTRY_ORIGIN_COMMUNITY_MAX",
    "DN42_COUNTRY_ORIGIN_COMMUNITY_MIN",
    "DN42_COUNTRY_ORIGIN_OFFSET",
    "DN42_IPV4_SPACE",
    "DN42_IPV6_SPACE",
    "DN42_RESERVED_IPV4_PREFIXES",
    "DN42_STANDARD_ORIGIN_REGION_COMMUNITIES",
    "DN42_TRANSFER_IPV4_PREFIXES",
    "Dn42OriginRegionCommunity",
    "LABEL_COMPONENT",
    "LABEL_CONFIG_HASH",
    "LABEL_MANAGED",
    "LABEL_MANAGED_VALUE",
    "LABEL_NODE_ID",
    "PRIVATE_ASN_16BIT_RANGE",
    "PRIVATE_ASN_32BIT_RANGE",
    "agent_id_for",
    "atomic_write_json",
    "atomic_write_text",
    "canonical_json_dumps",
    "canonical_sha256_hex",
    "container_labels",
    "create_environment",
    "derive_wireguard_public_key",
    "dn42_country_origin_community",
    "generate_recovery_keypair",
    "generate_wireguard_keypair",
    "recovery_key_fingerprint",
    "seal_to_recovery_key",
    "unseal_with_recovery_key",
    "is_address_in_prefix",
    "is_agent_token",
    "is_dn42_address",
    "is_dn42_anycast_address",
    "is_dn42_anycast_network",
    "is_dn42_closed_network",
    "is_dn42_ipv4_address",
    "is_dn42_ipv4_network",
    "is_dn42_ipv6_address",
    "is_dn42_ipv6_network",
    "is_dn42_network",
    "is_dn42_reserved_network",
    "is_dn42_transfer_network",
    "is_dn42_zone",
    "is_domain_name",
    "is_ipv6_link_local",
    "is_private_asn",
    "is_valid_dn42_country_origin_community",
    "is_wireguard_key",
    "network_labels",
    "node_id_filter",
    "node_project_name",
    "normalize_identifier",
    "service_container_name",
    "shell_quote",
    "split_ipv6_zone",
    "validate_agent_token",
    "validate_asn",
    "validate_dn42_ipv4_network",
    "validate_dn42_ipv6_network",
    "validate_domain_name",
    "validate_hostname",
    "validate_ip_address",
    "validate_ip_address_with_optional_zone",
    "validate_ip_interface",
    "validate_ip_network",
    "validate_ipv6_link_local_address",
    "validate_iso8601_timestamp",
    "validate_wireguard_endpoint",
    "validate_wireguard_key",
    "yaml_quote",
]
