



# 会话类型：IPv4
protocol bgp demopeer_4242420001_ex01_v4 from dnpeers {

    neighbor 172.20.0.105 as 4242420001;
    interface "as4242420001";
    passive on;


    bfd yes;


    ipv4 {
        import where dn42_import_filter(0,23,34);
        export where dn42_export_filter(0,23,34);
        import limit 8500 action block;
        import table;
    };
}

# 会话类型：IPv6
protocol bgp demopeer_4242420001_ex01_v6 from dnpeers {

    neighbor fdce:1111:2222:dead::11 as 4242420001;
    interface "as4242420001";
    passive on;


    bfd yes;


    ipv6 {
        import where dn42_import_filter(0,23,34);
        export where dn42_export_filter(0,23,34);
        import limit 8500 action block;
        import table;
    };
}

