# 由模板生成









protocol bgp ibgp_edge2 {
    local as 4242420000;
        neighbor fdce:1111:2222:ff01::3 as 4242420000;
    source address fdce:1111:2222:9500::1;

    advertise hostname on;

    ipv4 {
        import where ibgp_import_filter();

        export where ibgp_export_filter();

        next hop address 172.20.0.62;
        next hop self ebgp;
        import table;
    };

    ipv6 {
        import where ibgp_import_filter();

        export where ibgp_export_filter();

        next hop address fdce:1111:2222:9500::1;
        next hop self ebgp;
        import table;
    };
}




