from __future__ import annotations

"""管理面字面量 token 的形状校验。

运维显式指定 ``token`` 字面量时，agent / enrollment token 必须是 base64url 且
达到最小熵长度——挡掉弱口令与被截断的 token。不指定 ``token`` 时走自动生成路径，
不受此校验影响（回归这一点很关键，避免误伤常规签发）。
"""

from fastapi.testclient import TestClient

from app.core.config import ControlServerConfig

# 22+ 个 base64url 字符，通过校验。
_GOOD = "aZ0_-bcdefghijklmnopqrstuvwx"
# 含 base64url 字母表之外的字符（点号）。
_BAD_CHARS = "bad.token.with.dots.aaaaaaaa"
# 太短。
_BAD_SHORT = "short"


def _node_id(config: ControlServerConfig) -> str:
    return config.bootstrap_node_id


def test_issue_agent_token_rejects_bad_literal(client: TestClient, config: ControlServerConfig) -> None:
    node_id = _node_id(config)
    r = client.post(f"/api/v1/admin/nodes/{node_id}/agent-tokens", json={"token": _BAD_CHARS})
    assert r.status_code == 400
    r = client.post(f"/api/v1/admin/nodes/{node_id}/agent-tokens", json={"token": _BAD_SHORT})
    assert r.status_code == 400


def test_issue_agent_token_accepts_good_literal(client: TestClient, config: ControlServerConfig) -> None:
    node_id = _node_id(config)
    r = client.post(f"/api/v1/admin/nodes/{node_id}/agent-tokens", json={"token": _GOOD})
    assert r.status_code == 201, r.text
    assert r.json()["token"] == _GOOD


def test_issue_agent_token_autogenerated_still_works(client: TestClient, config: ControlServerConfig) -> None:
    # 不传 token：自动生成 <id>.<secret>（含点号），不应被字面量校验误伤。
    node_id = _node_id(config)
    r = client.post(f"/api/v1/admin/nodes/{node_id}/agent-tokens", json={})
    assert r.status_code == 201, r.text
    assert "." in r.json()["token"]


def test_create_enrollment_token_rejects_bad_literal(client: TestClient) -> None:
    r = client.post("/api/v1/admin/enrollment-tokens", json={"token": _BAD_CHARS})
    assert r.status_code == 400
    r = client.post("/api/v1/admin/enrollment-tokens", json={"token": _BAD_SHORT})
    assert r.status_code == 400


def test_create_enrollment_token_accepts_good_literal(client: TestClient) -> None:
    r = client.post("/api/v1/admin/enrollment-tokens", json={"token": _GOOD})
    assert r.status_code == 201, r.text


def test_create_enrollment_token_autogenerated_still_works(client: TestClient) -> None:
    r = client.post("/api/v1/admin/enrollment-tokens", json={"description": "auto"})
    assert r.status_code == 201, r.text
